---
- include_tasks:
    file: telegraf.yml
    apply:
      tags: ["telegraf"]
  when: telegraf_enabled
  tags:
    - always

- include_tasks:
    file: autoping.yml
    apply:
      tags: ["telegraf","telegraf:ping"]
  when: telegraf_enabled and telegraf_autoping
  tags:
    - always
